version: '3.9'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"

  krakend:
    build: 
      context: ./krakend/
    ports:
      - "8080:8080"
    depends_on:
      - backend
    env_file:
      - .env